package constant

import (
	"time"
)

const STATUS_WAITING_FOR_PRINTING = "STATUS_WAITING_FOR_PRINTING"
const STATUS_SUCCESSFUL_PRINTED = "STATUS_SUCCESSFUL_PRINTED"
const STATUS_WAITING_FOR_RETURN_PAGES = "STATUS_WAITING_FOR_RETURN_PAGES"
const TIME_OVERSIGHT_FOR_PRINTING = time.Hour * 24 * 7
const TIME_RETIRED_OLD_FILE = time.Minute * 2
const TIME_OFTEN_REPEAT_ADD_NEW_FILE = time.Second * 2
const TIME_OFTEN_REPEAT_PRINT_FILE= time.Second * 2
